# Generated by Django 6.0.3 on 2026-04-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported status'), ('VERIFIED', 'Verified status'), ('IN_PROGRESS', 'In Progress status'), ('RESOLVED', 'Resolved status')], default='REPORTED', max_length=20),
        ),
    ]
